/* Bloc « PAIEMENT LOCATAIRE » de web/app/index.html. Lancer : node web/paiement-front.test.js */
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, 'app/index.html'), 'utf8');
const m = html.match(/\/\/ ── PAIEMENT LOCATAIRE \(debut\) ──\n([\s\S]*?)\/\/ ── PAIEMENT LOCATAIRE \(fin\) ──/);
assert.ok(m, 'bloc PAIEMENT LOCATAIRE introuvable');
const ctx = {}; vm.createContext(ctx); vm.runInContext(m[1] + '\nthis.f = blocPaiementLocataire;', ctx);
const f = ctx.f;
const row = (paiements, pai, cau, status = 'signed') => ({ type: 'presentiel', status, payload: { paiements, total: '650', caution: '3000' }, paiement: pai, caution: cau });

let b = f(row(['Carte bancaire en ligne'], { status: 'attente' }, { status: 'carte_manquante', mode: 'auto' }));
assert.strictEqual(b.visible, true);
assert.match(b.bouton, /Payer 650,00\s€ et enregistrer ma carte/);
b = f(row(['Virement bancaire'], { status: 'attente' }, { status: 'carte_manquante', mode: 'auto' }));
assert.match(b.bouton, /Enregistrer ma carte pour la caution de 3\s000,00\s€/);
assert.match(b.info, /aucun débit/i);
b = f(row(['Virement bancaire'], { status: 'attente' }, { status: 'echec', mode: 'auto' }));
assert.strictEqual(b.visible, true, 'carte en echec : reenregistrement possible');
b = f(row(['Carte bancaire en ligne'], { status: 'paye_en_ligne' }, { status: 'carte_ok', mode: 'auto' }));
assert.strictEqual(b.visible, false);
assert.match(b.info, /Payé/);
b = f(row(['Virement bancaire'], { status: 'attente' }, { status: 'manuel', mode: 'manuel' }));
assert.strictEqual(b.visible, false);
b = f(row(['Virement bancaire'], { status: 'attente' }, { status: 'carte_manquante' }, 'pending'));
assert.strictEqual(b.visible, false, 'pas avant la signature');
b = f({ ...row(['Virement bancaire'], { status: 'attente' }, { status: 'carte_manquante', mode: 'auto' }), type: 'edl_depart' });
assert.strictEqual(b.visible, false, 'pas sur un lien d EDL');
b = f({ ...row(['Virement bancaire'], { status: 'attente' }, { status: 'carte_manquante', mode: 'auto' }), payload: { paiements: ['Virement bancaire'], total: '650' } });
assert.strictEqual(b.bouton, 'Enregistrer ma carte pour la caution', 'sans montant de caution : pas de 0,00 €');
assert.ok(!/0,00/.test(b.bouton + b.info));
// locTogPay : le slug est tronque a 8 caracteres, la table map doit contenir carteban
assert.match(html, /const map=\{[^}]*carteban:'enligne'/, 'map locTogPay sans carteban');
assert.ok(html.includes('id="locp_enligne"') && html.includes('id="locpc_enligne"'));
assert.strictEqual('Carte bancaire en ligne'.toLowerCase().replace(/[^a-z]/g, '').slice(0, 8), 'carteban');
const m2 = html.match(/\/\/ ── PASTILLES ADMIN \(debut\) ──\n([\s\S]*?)\/\/ ── PASTILLES ADMIN \(fin\) ──/);
assert.ok(m2, 'bloc PASTILLES ADMIN introuvable');
const ctx2 = {}; vm.createContext(ctx2); vm.runInContext(m2[1] + '\nthis.f = pastillesPaiement;', ctx2);
const P = ctx2.f;
const C = (pai, cau, payload = { paiements: ['Virement bancaire'], caution: '3000' }) => ({ status: 'signed', payload, paiement: pai, caution: cau });
let r = P(C({ status: 'attente' }, { status: 'carte_manquante', mode: 'auto' }));
assert.strictEqual(r.paiement.texte, 'En attente (Virement bancaire)');
assert.strictEqual(r.caution.texte, 'Carte manquante');
assert.deepStrictEqual([...r.actions].sort(), ['caution_manuelle', 'marquer_paye']);
r = P(C({ status: 'paye_en_ligne' }, { status: 'bloquee', mode: 'auto', expire_vers: '2026-10-14T10:00:00Z', montant_cents: 300000 }));
assert.strictEqual(r.paiement.texte, 'Payé en ligne ✓');
assert.match(r.caution.texte, /^Bloquée jusqu’au 14\/10/);
assert.deepStrictEqual([...r.actions].sort(), ['liberer', 'retenir']);
r = P(C({ status: 'paye_manuel', mode: 'Espèces' }, { status: 'echec', mode: 'auto', dernier_motif: 'insufficient_funds', echecs: 3 }));
assert.strictEqual(r.paiement.texte, 'Payé (déclaré, Espèces)');
assert.strictEqual(r.caution.ton, 'alerte');
assert.ok(r.actions.includes('poser') && r.actions.includes('annuler_paye') && r.actions.includes('caution_manuelle'));
r = P(C({}, { status: 'retenue', mode: 'auto', retenu_cents: 45000 }));
assert.match(r.caution.texte, /^Retenue 450,00\s€$/);
r = P(C({}, { status: 'manuel', mode: 'manuel' }));
assert.strictEqual(r.caution.texte, 'Gérée hors ligne');
assert.ok(r.actions.includes('caution_auto'));
// liaison : rechargement de la liste, ecran Retour restreint aux contrats presentiel/distance
assert.ok(html.includes('loadContractsList(currentContractsFilter);\n}'), 'opPaiement doit recharger Mes contrats');
assert.ok(!html.includes("typeof loadContracts==='function'"));
assert.ok(html.includes("(parent.data?.type==='presentiel'||parent.data?.type==='distance')&&parent.data?.caution?.status==='bloquee'"));
assert.match(html, /\.select\('id,code,access_token,type,vehicle,status,payload,[^']*,paiement,caution'\)/);
console.log('paiement-front : OK');
